"""Shell completion script generator.

This module generates shell-specific completion scripts for bash, zsh, and fish.
The generated scripts integrate with each shell's native completion system.

Ownership: Workstream G (UX/docs)
"""

from __future__ import annotations

from typing import Literal

ShellType = Literal["bash", "zsh", "fish"]

# Template for bash completion script
BASH_COMPLETION_TEMPLATE = '''# devflow bash completion
# Generated by devflow completion bash
# Add to ~/.bashrc: eval "$(devflow completion bash)"

_devflow_completion() {
    local cur prev words cword
    _init_completion || return

    local commands="venv deps test build publish task ci-check completion version"
    local global_opts="--config --project-root --verbose -v --quiet -q --dry-run --version --help"

    case "${prev}" in
        devflow)
            COMPREPLY=($(compgen -W "${commands} ${global_opts}" -- "${cur}"))
            return 0
            ;;
        venv)
            COMPREPLY=($(compgen -W "init --help" -- "${cur}"))
            return 0
            ;;
        deps)
            COMPREPLY=($(compgen -W "sync freeze --help" -- "${cur}"))
            return 0
            ;;
        init)
            COMPREPLY=($(compgen -W "--python --recreate --help" -- "${cur}"))
            return 0
            ;;
        sync)
            COMPREPLY=($(compgen -W "--dev --extras --help" -- "${cur}"))
            return 0
            ;;
        freeze)
            COMPREPLY=($(compgen -W "--output --help" -- "${cur}"))
            return 0
            ;;
        test)
            COMPREPLY=($(compgen -W "--pattern --marker --cov --help" -- "${cur}"))
            return 0
            ;;
        build)
            COMPREPLY=($(compgen -W "--clean --wheel-only --sdist-only --help" -- "${cur}"))
            return 0
            ;;
        publish)
            COMPREPLY=($(compgen -W "--repository --allow-dirty --skip-tests --skip-build --help" -- "${cur}"))
            return 0
            ;;
        task)
            # TODO: Dynamic task completion from config
            # Workstream A's config loader will provide task discovery via AppContext.
            # When integrated, this section should call a helper function to read
            # [tool.devflow.tasks.*] sections and return task names for completion.
            # Example: _get_project_tasks() -> list[str]
            COMPREPLY=($(compgen -W "--help" -- "${cur}"))
            return 0
            ;;
        ci-check)
            COMPREPLY=($(compgen -W "--continue-on-error --help" -- "${cur}"))
            return 0
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh fish" -- "${cur}"))
            return 0
            ;;
        --config|--project-root)
            # File/directory completion
            _filedir
            return 0
            ;;
        --python)
            # Python interpreter completion
            COMPREPLY=($(compgen -c python -- "${cur}"))
            return 0
            ;;
        --repository)
            COMPREPLY=($(compgen -W "pypi testpypi" -- "${cur}"))
            return 0
            ;;
    esac

    # Default to completing commands and global options
    if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "${global_opts}" -- "${cur}"))
    else
        COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
    fi
}

complete -F _devflow_completion devflow
'''

# Template for zsh completion script
ZSH_COMPLETION_TEMPLATE = '''#compdef devflow
# devflow zsh completion
# Generated by devflow completion zsh
# Add to ~/.zshrc: eval "$(devflow completion zsh)"

_devflow() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \\
        '--config[Path to configuration file]:config file:_files' \\
        '--project-root[Override project root detection]:directory:_directories' \\
        '(-v --verbose)'{-v,--verbose}'[Increase verbosity]' \\
        '(-q --quiet)'{-q,--quiet}'[Suppress non-essential output]' \\
        '--dry-run[Preview actions without executing]' \\
        '--version[Show version and exit]' \\
        '--help[Show help message]' \\
        '1:command:_devflow_commands' \\
        '*::arg:->args'

    case $state in
        args)
            case $words[1] in
                venv)
                    _arguments \\
                        '1:subcommand:(init)' \\
                        '--python[Python interpreter to use]:python:_command_names -e' \\
                        '--recreate[Delete and recreate existing venv]' \\
                        '--help[Show help]'
                    ;;
                deps)
                    _arguments \\
                        '1:subcommand:(sync freeze)' \\
                        '--dev[Include development dependencies]' \\
                        '--extras[Install optional extras]' \\
                        '--output[Output file for freeze]:file:_files' \\
                        '--help[Show help]'
                    ;;
                test)
                    _arguments \\
                        '--pattern[Test file pattern]:pattern:' \\
                        '--marker[Run tests matching marker]:marker:' \\
                        '--cov[Enable coverage reporting]' \\
                        '--help[Show help]' \\
                        '*:args:'
                    ;;
                build)
                    _arguments \\
                        '--clean[Clean dist directory before building]' \\
                        '--wheel-only[Build wheel only]' \\
                        '--sdist-only[Build sdist only]' \\
                        '--help[Show help]'
                    ;;
                publish)
                    _arguments \\
                        '--repository[Target repository]:repository:(pypi testpypi)' \\
                        '--allow-dirty[Publish with uncommitted changes]' \\
                        '--skip-tests[Skip pre-publish tests]' \\
                        '--skip-build[Use existing dist artifacts]' \\
                        '--help[Show help]'
                    ;;
                task)
                    # TODO: Dynamic task completion from config
                    # Workstream A's config loader will provide task discovery via AppContext.
                    # When integrated, this section should call a helper function to read
                    # [tool.devflow.tasks.*] sections and return task names for completion.
                    _arguments \\
                        '1:task name:' \\
                        '--help[Show help]' \\
                        '*:args:'
                    ;;
                ci-check)
                    _arguments \\
                        '--continue-on-error[Continue pipeline even if a step fails]' \\
                        '--help[Show help]'
                    ;;
                completion)
                    _arguments \\
                        '1:shell:(bash zsh fish)'
                    ;;
            esac
            ;;
    esac
}

_devflow_commands() {
    local commands=(
        'venv:Manage project virtual environment'
        'deps:Manage dependencies (sync, freeze)'
        'test:Run tests using configured test runner'
        'build:Build distribution artifacts'
        'publish:Build and upload to package index'
        'task:Run custom tasks defined in config'
        'ci-check:Run CI pipeline (lint, test, build)'
        'completion:Generate shell completion script'
    )
    _describe 'command' commands
}

_devflow "$@"
'''

# Template for fish completion script
FISH_COMPLETION_TEMPLATE = '''# devflow fish completion
# Generated by devflow completion fish
# Add to ~/.config/fish/config.fish: devflow completion fish | source

# Disable file completion by default
complete -c devflow -f

# Global options
complete -c devflow -l config -d 'Path to configuration file' -r -F
complete -c devflow -l project-root -d 'Override project root detection' -r -a '(__fish_complete_directories)'
complete -c devflow -s v -l verbose -d 'Increase verbosity'
complete -c devflow -s q -l quiet -d 'Suppress non-essential output'
complete -c devflow -l dry-run -d 'Preview actions without executing'
complete -c devflow -l version -d 'Show version and exit'
complete -c devflow -s h -l help -d 'Show help message'

# Commands
complete -c devflow -n __fish_use_subcommand -a venv -d 'Manage project virtual environment'
complete -c devflow -n __fish_use_subcommand -a deps -d 'Manage dependencies (sync, freeze)'
complete -c devflow -n __fish_use_subcommand -a test -d 'Run tests using configured test runner'
complete -c devflow -n __fish_use_subcommand -a build -d 'Build distribution artifacts'
complete -c devflow -n __fish_use_subcommand -a publish -d 'Build and upload to package index'
complete -c devflow -n __fish_use_subcommand -a task -d 'Run custom tasks defined in config'
complete -c devflow -n __fish_use_subcommand -a ci-check -d 'Run CI pipeline (lint, test, build)'
complete -c devflow -n __fish_use_subcommand -a completion -d 'Generate shell completion script'

# venv subcommands
complete -c devflow -n '__fish_seen_subcommand_from venv' -a init -d 'Create or recreate the virtual environment'
complete -c devflow -n '__fish_seen_subcommand_from venv' -l python -d 'Python interpreter to use' -r
complete -c devflow -n '__fish_seen_subcommand_from venv' -l recreate -d 'Delete and recreate existing venv'

# deps subcommands
complete -c devflow -n '__fish_seen_subcommand_from deps' -a sync -d 'Install dependencies from requirements files'
complete -c devflow -n '__fish_seen_subcommand_from deps' -a freeze -d 'Freeze installed packages to file'
complete -c devflow -n '__fish_seen_subcommand_from deps' -l dev -d 'Include development dependencies'
complete -c devflow -n '__fish_seen_subcommand_from deps' -l extras -d 'Install optional extras'
complete -c devflow -n '__fish_seen_subcommand_from deps' -l output -d 'Output file for freeze' -r -F

# test options
complete -c devflow -n '__fish_seen_subcommand_from test' -l pattern -d 'Test file pattern' -r
complete -c devflow -n '__fish_seen_subcommand_from test' -l marker -d 'Run tests matching marker' -r
complete -c devflow -n '__fish_seen_subcommand_from test' -l cov -d 'Enable coverage reporting'

# build options
complete -c devflow -n '__fish_seen_subcommand_from build' -l clean -d 'Clean dist directory before building'
complete -c devflow -n '__fish_seen_subcommand_from build' -l wheel-only -d 'Build wheel only'
complete -c devflow -n '__fish_seen_subcommand_from build' -l sdist-only -d 'Build sdist only'

# publish options
complete -c devflow -n '__fish_seen_subcommand_from publish' -l repository -d 'Target repository' -r -a 'pypi testpypi'
complete -c devflow -n '__fish_seen_subcommand_from publish' -l allow-dirty -d 'Publish with uncommitted changes'
complete -c devflow -n '__fish_seen_subcommand_from publish' -l skip-tests -d 'Skip pre-publish tests'
complete -c devflow -n '__fish_seen_subcommand_from publish' -l skip-build -d 'Use existing dist artifacts'

# ci-check options
complete -c devflow -n '__fish_seen_subcommand_from ci-check' -l continue-on-error -d 'Continue pipeline even if a step fails'

# completion subcommands
complete -c devflow -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish' -d 'Shell type'
'''


def generate_bash_completion() -> str:
    """Generate bash completion script.
    
    Returns:
        str: Complete bash completion script for devflow.
    """
    return BASH_COMPLETION_TEMPLATE


def generate_zsh_completion() -> str:
    """Generate zsh completion script.
    
    Returns:
        str: Complete zsh completion script for devflow.
    """
    return ZSH_COMPLETION_TEMPLATE


def generate_fish_completion() -> str:
    """Generate fish completion script.
    
    Returns:
        str: Complete fish completion script for devflow.
    """
    return FISH_COMPLETION_TEMPLATE


def get_completion_script(shell: ShellType) -> str:
    """Get completion script for the specified shell.
    
    Args:
        shell: The shell type ('bash', 'zsh', or 'fish').
        
    Returns:
        str: The completion script for the specified shell.
        
    Raises:
        ValueError: If shell type is not supported.
    """
    generators = {
        "bash": generate_bash_completion,
        "zsh": generate_zsh_completion,
        "fish": generate_fish_completion,
    }
    
    if shell not in generators:
        supported = ", ".join(generators.keys())
        raise ValueError(f"Unsupported shell: {shell}. Supported shells: {supported}")
    
    return generators[shell]()
