"""Tests for DepsManager dependency management."""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from devflow.commands.deps import DepsManager, create_deps_manager
from devflow.commands.venv import VenvManager


class TestDepsManager:
    """Tests for DepsManager dependency management."""

    @pytest.fixture
    def venv_project(self, tmp_path: Path):
        """Create a project with a virtual environment."""
        (tmp_path / "pyproject.toml").write_text("[project]\nname = 'test'\n")

        # Create venv
        venv_manager = VenvManager(
            project_root=tmp_path,
            venv_dir_name=".venv",
        )
        venv_manager.init()

        return tmp_path

    def test_deps_sync_no_venv(self, tmp_path: Path) -> None:
        """Test that deps sync fails when no venv exists."""
        (tmp_path / "pyproject.toml").write_text("[project]\nname = 'test'\n")

        manager = DepsManager(
            project_root=tmp_path,
            venv_dir_name=".venv",
        )

        result = manager.sync()
        assert result == 1  # Should fail

    def test_deps_sync_from_requirements(self, venv_project: Path) -> None:
        """Test deps sync from requirements.txt."""
        # Create a simple requirements file with a standard package
        (venv_project / "requirements.txt").write_text("pip>=21.0\n")

        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
            verbose=True,
        )

        result = manager.sync()
        assert result == 0

    def test_deps_sync_dry_run(self, venv_project: Path) -> None:
        """Test deps sync dry run mode."""
        (venv_project / "requirements.txt").write_text("requests\n")

        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
            dry_run=True,
        )

        result = manager.sync()
        assert result == 0  # Should succeed without actually installing

    def test_deps_sync_no_requirements(self, venv_project: Path) -> None:
        """Test deps sync when no requirements files exist."""
        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
        )

        result = manager.sync()
        assert result == 0  # Should succeed with nothing to do

    def test_deps_freeze_basic(self, venv_project: Path) -> None:
        """Test deps freeze creates a freeze file."""
        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
            freeze_output="requirements-freeze.txt",
        )

        result = manager.freeze()
        assert result == 0

        freeze_file = venv_project / "requirements-freeze.txt"
        assert freeze_file.exists()

        content = freeze_file.read_text()
        assert "# This file is auto-generated by devflow deps freeze" in content

    def test_deps_freeze_deterministic_ordering(self, venv_project: Path) -> None:
        """Test that deps freeze output is deterministically ordered."""
        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
            freeze_output="requirements-freeze.txt",
        )

        # Freeze twice
        manager.freeze()
        content1 = (venv_project / "requirements-freeze.txt").read_text()

        manager.freeze()
        content2 = (venv_project / "requirements-freeze.txt").read_text()

        # Output should be identical
        assert content1 == content2

    def test_deps_freeze_dry_run(self, venv_project: Path) -> None:
        """Test deps freeze dry run mode."""
        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
            freeze_output="requirements-freeze.txt",
            dry_run=True,
        )

        result = manager.freeze()
        assert result == 0

        # File should not be created in dry run
        freeze_file = venv_project / "requirements-freeze.txt"
        assert not freeze_file.exists()

    def test_deps_freeze_custom_output(self, venv_project: Path) -> None:
        """Test deps freeze with custom output path."""
        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
            freeze_output="custom-freeze.txt",
        )

        result = manager.freeze()
        assert result == 0

        freeze_file = venv_project / "custom-freeze.txt"
        assert freeze_file.exists()

    def test_deps_list(self, venv_project: Path) -> None:
        """Test deps list command."""
        manager = DepsManager(
            project_root=venv_project,
            venv_dir_name=".venv",
        )

        result = manager.list()
        assert result == 0

    def test_create_deps_manager_factory(self, tmp_path: Path) -> None:
        """Test the create_deps_manager factory function."""
        (tmp_path / "pyproject.toml").write_text("[project]\nname = 'test'\n")

        original_cwd = os.getcwd()
        try:
            os.chdir(tmp_path)
            manager = create_deps_manager(
                venv_dir=".venv",
                freeze_output="freeze.txt",
                verbose=True,
            )
            assert manager.project_root == tmp_path.resolve()
            assert manager.venv_dir_name == ".venv"
            assert manager.freeze_output == "freeze.txt"
            assert manager.verbose is True
        finally:
            os.chdir(original_cwd)
